pipeline {
    agent any 

    tools {
        gradle 'gradle-baran-clinic'
    }

    stages {
        stage('Unit Tests - Backend') {
            steps {
                echo 'Running Unit Tests'
                withGradle() {
                    sh 'gradle clean test'
                }
            }
        }
    }
}
