pipeline {
    agent any 

    tools {
        gradle 'gradle-baran-clinic'
    }

    stages {
        stage('Unit Tests - Backend') {
            steps {
                    withGradle() {
                        dir ('src/test/java/com/example/baranclinic/crm/domain/service') {
                        sh './gradlew clean test'
                    }
                }
            }
        }
    }
}
