pipeline {
    agent {
        docker {
            image 'gradle:9.4-jdk21'
            reuseNode true
        }
    }

    stages {
        stage('Unit Tests - Backend') {
            steps {
                dir('srs/test') {
                    sh './gradlew clean test'
                }
            }
        }
    }
}
